<a href="https://colab.research.google.com/github/sheep1008/py/blob/main/Numpy%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Numpy 도입
import numpy as np

In [2]:
# Numpy 배열
# Python의 리스트로부터 Numpy 배열을 만든다.

a=np.array([0,1,2,3,4,5])
print(a)

[0 1 2 3 4 5]


In [5]:
# 2차원의 배열을 만들기
b = np.array([[0,1,2],[3,4,5]])
# 2중 리스트로부터 NumPy의 2차원 배열을 만든다.
print(b)

[[0 1 2]
 [3 4 5]]


In [7]:
#3중 리스트로부터 NumPy의 3차원 배열을 만든다.
c=np.array([[[0,1,2], [1,2,3]], [[2,3,4,], [3,4,5]]])
print(c)

[[[0 1 2]
  [1 2 3]]

 [[2 3 4]
  [3 4 5]]]


In [9]:
#배열의 연산
a=np.array([[0,1,2],[3,4,5]])

print(a)
print()
print(a+2) #각 요소에 2를 더한다.
print()
print(a*2) #각 요소에 2를 곱한다.

[[0 1 2]
 [3 4 5]]

[[2 3 4]
 [5 6 7]]

[[ 0  2  4]
 [ 6  8 10]]


In [10]:
b=np.array([[0,1,2], [3,4,5]])
c=np.array([[1,2,3], [4,5,6]])

print(b)
print()
print(c)
print()
print(b+c) #요소끼리의 합
print()
print(b*c) #요소끼리의 곱

[[0 1 2]
 [3 4 5]]

[[1 2 3]
 [4 5 6]]

[[ 1  3  5]
 [ 7  9 11]]

[[ 0  2  6]
 [12 20 30]]


In [11]:
#브로드 캐스트 - 다른 차원의 배열끼리의 연산
d=np.array([[1,1], [1,1]]) # 2차원 배열
e=np.array([1,2]) # 1차원 배열

print(d)
print()
print(e)
print()
print(d+e) #브로드캐스트의 적용

[[1 1]
 [1 1]]

[1 2]

[[2 3]
 [2 3]]


배열의 형태를 얻을 수 있다.

shape()에 의해 행과 열을 알 수 있다. / reshape()에 의해 배열의 형태를 변환할 수 있다.

In [14]:
# shape에 의해 배열의 형태를 얻음
a=np.array([[0,1,2], [3,4,5]])
print(a.shape) #배열 a의 형태를 표시

(2, 3)


In [16]:
# reshape에 의해 배열의 형태를 변환
b=np.array([0,1,2,3,4,5,6,7,8,9,10,11]) #배열의 작성
c=b.reshape(3,4) #(3,4)인 2차원 배열로 변환

print(b) # 원본 배열
print()
print(c) #형태를 변환한 배열

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
# reshape(-1)을 하면 어떤 형태의 배열이라도 1차원 배열로 변환할 수 있다
d=np.array([[[0,1,2], [3,4,5]], [[5,4,3],[2,1,0]]])
e=d.reshape(-1)

print(d)
print()
print(e)

[[[0 1 2]
  [3 4 5]]

 [[5 4 3]
  [2 1 0]]]

[0 1 2 3 4 5 5 4 3 2 1 0]


요소로의 접근

In [19]:
#인덱스를 사용하여 접근
a=np.array([0,1,2,3,4,5,6])
print(a[3])

3


In [20]:
#인덱스를 지정하여 배열 요소 교체하기
a[3]=99
print(a)

[ 0  1  2 99  4  5  6]


In [21]:
# 2차원 배열 요소 접근하기
b=np.array([[0,1,2], [3,4,5]])

print(b[1,0]) #b[1][0]과 같다.

3


In [22]:
b[1][0]
print(b)

[[0 1 2]
 [3 4 5]]


In [25]:
def a_func(x):
  y=x*2+1
  return y

a=np.array([[0,1,2], [3,4,5]]) #2차원 배열
b=a_func(a) #인수로서 배열을 전달

print(a)
print()
print(b)

[[0 1 2]
 [3 4 5]]

[[ 1  3  5]
 [ 7  9 11]]


NumPy의 다양한 연산 기능

sum으로 합계, average로 평균, min으로 최솟값, max로 최댓값을 계산

In [27]:
a=np.array([[1,2,3], [4,5,6]])
print(np.sum(a)) #합
print(np.average(a)) #평균
print(np.min(a)) #최솟값
print(np.max(a)) #최댓값

21
3.5
1
6


In [28]:
# axis를 지정하면 특정 방향으로 연산이 이뤄진다.
a=np.array([[1,2,3], [4,5,6]])

print(np.average(a, axis=0)) #열의 평균(세로 방향에서 평균)
print(np.average(a, axis=1)) #행의 평균(가로 방향에서 평균)

[2.5 3.5 4.5]
[2. 5.]
